// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "catalog/catalog.proto" (package "catalog", syntax proto3)
// tslint:disable
import { ToggleAttachProductsToTagsParams } from "./products";
import { ToggleAttachProductsToBrandsParams } from "./products";
import { CommonToggleAttachProductsResponse } from "./products";
import { ToggleAttachProductsToCategoryParams } from "./products";
import { CheckProductAvailableSlugParams } from "./products";
import { UpdateProductsPricesResponse } from "./products";
import { UpdateProductsPricesParams } from "./products";
import { UpdateProductsStocksResponse } from "./products";
import { UpdateProductsStocksParams } from "./products";
import { UpdateProductsStatusResponse } from "./products";
import { UpdateProductsStatusParams } from "./products";
import { UpdateProductMetaParams } from "./products";
import { CreateProductParams } from "./products";
import { Product } from "./products";
import { GetProductByUuidParams } from "./products";
import { GetProductsResponse } from "./products";
import { GetProductsByUuidsParams } from "./products";
import { GetProductsShortOffsetResponse } from "./products";
import { GetProductsShortOffsetParams } from "./products";
import { GetProductsOffsetResponse } from "./products";
import { GetProductsOffsetParams } from "./products";
import { GetProductsShortPaginateResponse } from "./products";
import { GetProductsShortPaginateParams } from "./products";
import { GetProductsPaginateResponse } from "./products";
import { GetProductsPaginateParams } from "./products";
import { CheckAvailableSlugParams } from "./categories";
import { UpdateOrderSortToCategoriesResponse } from "./categories";
import { UpdateOrderSortToCategoriesParams } from "./categories";
import { Status } from "../common/common";
import { SetImageToCategoryParams } from "./categories";
import { DeleteCategoriesResponse } from "./categories";
import { DeleteCategoriesParams } from "./categories";
import { UpdateCategoryParams } from "./categories";
import { CreateCategoryParams } from "./categories";
import { CategoryShort } from "./categories";
import { Category } from "./categories";
import { GetCategoryByIdParams } from "./categories";
import { GetCategoriesShortOffsetResponse } from "./categories";
import { GetCategoriesShortOffsetParams } from "./categories";
import { GetCategoriesOffsetResponse } from "./categories";
import { GetCategoriesOffsetParams } from "./categories";
import { GetCategoriesShortPaginateResponse } from "./categories";
import { GetCategoriesPaginateResponse } from "./categories";
import { GetCategoriesPaginateParams } from "./categories";
import { DeleteBrandsResponse } from "./brands";
import { DeleteBrandsParams } from "./brands";
import { UpdateBrandParams } from "./brands";
import { CreateBrandParams } from "./brands";
import { BrandShort } from "./brands";
import { Brand } from "./brands";
import { GetBrandByIdParams } from "./brands";
import { GetBrandsShortOffsetResponse } from "./brands";
import { GetOffsetBrandsShortParams } from "./brands";
import { GetBrandsOffsetResponse } from "./brands";
import { GetOffsetBrandsParams } from "./brands";
import { GetBrandsShortPaginateResponse } from "./brands";
import { GetBrandsPaginateResponse } from "./brands";
import { GetBrandsPaginateParams } from "./brands";
import { CheckAvailableTagNamesResponse } from "./tags";
import { CheckAvailableTagNamesParams } from "./tags";
import { DeleteTagsResponse } from "./tags";
import { DeleteTagsParams } from "./tags";
import { UpdateTagParams } from "./tags";
import { CreateTagParams } from "./tags";
import { Tag } from "./tags";
import { GetTagByIdParams } from "./tags";
import { GetTagsShortOffsetResponse } from "./tags";
import { GetTagsShortOffsetParams } from "./tags";
import { GetTagsOffsetResponse } from "./tags";
import { GetTagsOffsetParams } from "./tags";
import { GetTagsShortPaginateResponse } from "./tags";
import { GetTagsShortPaginateParams } from "./tags";
import { GetTagsPaginateResponse } from "./tags";
import { GetTagsPaginateParams } from "./tags";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service catalog.Catalog
 */
export const Catalog = new ServiceType("catalog.Catalog", [
    { name: "GetTagsPaginate", options: {}, I: GetTagsPaginateParams, O: GetTagsPaginateResponse },
    { name: "GetTagsShortPaginate", options: {}, I: GetTagsShortPaginateParams, O: GetTagsShortPaginateResponse },
    { name: "GetTagsOffset", options: {}, I: GetTagsOffsetParams, O: GetTagsOffsetResponse },
    { name: "GetTagsShortOffset", options: {}, I: GetTagsShortOffsetParams, O: GetTagsShortOffsetResponse },
    { name: "GetTagById", options: {}, I: GetTagByIdParams, O: Tag },
    { name: "CreateTag", options: {}, I: CreateTagParams, O: Tag },
    { name: "UpdateTag", options: {}, I: UpdateTagParams, O: Tag },
    { name: "DeleteTags", options: {}, I: DeleteTagsParams, O: DeleteTagsResponse },
    { name: "CheckAvailableTagNames", options: {}, I: CheckAvailableTagNamesParams, O: CheckAvailableTagNamesResponse },
    { name: "GetBrandsPaginate", options: {}, I: GetBrandsPaginateParams, O: GetBrandsPaginateResponse },
    { name: "GetBrandsShortPaginate", options: {}, I: GetBrandsPaginateParams, O: GetBrandsShortPaginateResponse },
    { name: "GetBrandsOffset", options: {}, I: GetOffsetBrandsParams, O: GetBrandsOffsetResponse },
    { name: "GetBrandsShortOffset", options: {}, I: GetOffsetBrandsShortParams, O: GetBrandsShortOffsetResponse },
    { name: "GetBrandById", options: {}, I: GetBrandByIdParams, O: Brand },
    { name: "GetBrandShortById", options: {}, I: GetBrandByIdParams, O: BrandShort },
    { name: "CreateBrand", options: {}, I: CreateBrandParams, O: Brand },
    { name: "UpdateBrand", options: {}, I: UpdateBrandParams, O: Brand },
    { name: "DeleteBrands", options: {}, I: DeleteBrandsParams, O: DeleteBrandsResponse },
    { name: "GetCategoriesPaginate", options: {}, I: GetCategoriesPaginateParams, O: GetCategoriesPaginateResponse },
    { name: "GetCategoriesShortPaginate", options: {}, I: GetCategoriesPaginateParams, O: GetCategoriesShortPaginateResponse },
    { name: "GetCategoriesOffset", options: {}, I: GetCategoriesOffsetParams, O: GetCategoriesOffsetResponse },
    { name: "GetCategoriesShortOffset", options: {}, I: GetCategoriesShortOffsetParams, O: GetCategoriesShortOffsetResponse },
    { name: "GetCategoryById", options: {}, I: GetCategoryByIdParams, O: Category },
    { name: "GetCategoryShortById", options: {}, I: GetCategoryByIdParams, O: CategoryShort },
    { name: "CreateCategory", options: {}, I: CreateCategoryParams, O: Category },
    { name: "UpdateCategory", options: {}, I: UpdateCategoryParams, O: Category },
    { name: "DeleteCategories", options: {}, I: DeleteCategoriesParams, O: DeleteCategoriesResponse },
    { name: "SetImageToCategory", options: {}, I: SetImageToCategoryParams, O: Status },
    { name: "UpdateOrderSortToCategories", options: {}, I: UpdateOrderSortToCategoriesParams, O: UpdateOrderSortToCategoriesResponse },
    { name: "CheckCategoryAvailableSlug", options: {}, I: CheckAvailableSlugParams, O: Status },
    { name: "GetProductsPaginate", options: {}, I: GetProductsPaginateParams, O: GetProductsPaginateResponse },
    { name: "GetProductsShortPaginate", options: {}, I: GetProductsShortPaginateParams, O: GetProductsShortPaginateResponse },
    { name: "GetProductsOffset", options: {}, I: GetProductsOffsetParams, O: GetProductsOffsetResponse },
    { name: "GetProductsShortOffset", options: {}, I: GetProductsShortOffsetParams, O: GetProductsShortOffsetResponse },
    { name: "GetProductsByUuids", options: {}, I: GetProductsByUuidsParams, O: GetProductsResponse },
    { name: "GetProductByUuid", options: {}, I: GetProductByUuidParams, O: Product },
    { name: "CreateProduct", options: {}, I: CreateProductParams, O: Product },
    { name: "UpdateProduct", options: {}, I: UpdateProductMetaParams, O: Product },
    { name: "UpdateProductsStatus", options: {}, I: UpdateProductsStatusParams, O: UpdateProductsStatusResponse },
    { name: "UpdateProductsStocks", options: {}, I: UpdateProductsStocksParams, O: UpdateProductsStocksResponse },
    { name: "UpdateProductsPrices", options: {}, I: UpdateProductsPricesParams, O: UpdateProductsPricesResponse },
    { name: "CheckProductAvailableSlug", options: {}, I: CheckProductAvailableSlugParams, O: Status },
    { name: "AttachProductsToCategory", options: {}, I: ToggleAttachProductsToCategoryParams, O: CommonToggleAttachProductsResponse },
    { name: "DetachProductsToCategory", options: {}, I: ToggleAttachProductsToCategoryParams, O: CommonToggleAttachProductsResponse },
    { name: "AttachProductsToBrands", options: {}, I: ToggleAttachProductsToBrandsParams, O: CommonToggleAttachProductsResponse },
    { name: "DetachProductsToBrands", options: {}, I: ToggleAttachProductsToBrandsParams, O: CommonToggleAttachProductsResponse },
    { name: "AttachProductsToTags", options: {}, I: ToggleAttachProductsToTagsParams, O: CommonToggleAttachProductsResponse },
    { name: "DetachProductsToTags", options: {}, I: ToggleAttachProductsToTagsParams, O: CommonToggleAttachProductsResponse }
]);
